sudo: required
services:
  - docker
before_install:
  - docker build -t pciaco/appiad:latest .
script:
  - docker images pciaco/appiad
after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pciaco/appiad